version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15.3-alpine
    container_name: law-firm-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: law_firm_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - law-firm-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Node.js API Service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: law-firm-api
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: development
      PORT: 3001
      JWT_SECRET: your_jwt_secret_here_change_in_production
      JWT_EXPIRE: 30d
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: law_firm_db
      DB_USER: postgres
      DB_PASSWORD: postgres_password
    ports:
      - "3001:3001"
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - law-firm-network
    command: npm run dev

# Volume for persistent data
volumes:
  postgres_data:

# Network for service communication
networks:
  law-firm-network:
    driver: bridge
